title: Title here
author: merelj
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  i changed this description

# social links
github_username:  merelj

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
